### ISSUE TITLE
Installation dies

### ISSUE THREAD

**Issue by faddat** [ibravo/tripleo#1]
It insists I have an eth0, but I do not.  Sorry I can't be of much more help-- very green with regard to openstack.  

https://gist.github.com/faddat/b46d0a5c4c37563001fd

**Comment by ibravo** [comment]
faddat,

These scripts were used to deploy several configurations on a test environment and not intended to be 100% functional all the time. 

I recommend that you follow the latest installation steps on the RDO Manager documentation at: https://repos.fedorapeople.org/repos/openstack-m/rdo-manager-docs/liberty/

IB

**Comment by faddat** [comment]
Thanks!  Actually giving those scripts a go as we speak :).
